In [1]:
import os
import json
from pathlib import Path

import pandas as pd

In [4]:
data_path = Path("../data")

data_sources = os.listdir(data_path)
print(sorted(data_sources))

['2020-09-12T08-24-34Z_data.json', '2020-09-13T00-00-00Z_data.json', '2020-09-13T06-00-00Z_data.json', '2020-09-13T12-00-10Z_data.json', '2020-09-13T18-00-00Z_data.json', '2020-09-14T00-00-00Z_data.json', '2020-09-14T06-00-00Z_data.json']

In [8]:
print(Path(data_path, "2020-09-12T08-24-34Z_data.json"))

../data/2020-09-12T08-24-34Z_data.json

In [14]:
with open(Path(data_path, "2020-09-13T00-00-00Z_data.json")) as json_file:
        fpl_json_13 = json.load(json_file)
        
with open(Path(data_path, "2020-09-14T00-00-00Z_data.json")) as json_file:
        fpl_json_14 = json.load(json_file)

In [26]:
elements_df_13 = pd.DataFrame(fpl_json_13["elements"])
elements_df_14 = pd.DataFrame(fpl_json_14["elements"])

In [27]:
# Noe hacking av rekkefølge av index for å få ønskede verdier først
_elements_columns = elements_df_13.columns.tolist()
_elements_columns.insert(0, _elements_columns.pop(_elements_columns.index("team")))
_elements_columns.insert(0, _elements_columns.pop(_elements_columns.index("first_name")))
_elements_columns.insert(0, _elements_columns.pop(_elements_columns.index("second_name")))
elements_df_13 = elements_df_13[_elements_columns]
# Vis 5 første linjer
display(elements_df_13.head(5))

# Vis tilgjengelige kolonner
display(sorted(_elements_columns))

,second_name,first_name,team,chance_of_playing_next_round,chance_of_playing_this_round,code,cost_change_event,cost_change_event_fall,cost_change_start,cost_change_start_fall,...,threat_rank,threat_rank_type,ict_index_rank,ict_index_rank_type,corners_and_indirect_freekicks_order,corners_and_indirect_freekicks_text,direct_freekicks_order,direct_freekicks_text,penalties_order,penalties_text
0,Özil,Mesut,1,NaN,NaN,37605,0,0,0,0,...,491,192,492,192,3.0,,NaN,,NaN,
1,Papastathopoulos,Sokratis,1,0.0,0.0,39476,0,0,0,0,...,243,117,262,121,NaN,,NaN,,NaN,
2,Luiz Moreira Marinho,David,1,0.0,0.0,41270,0,0,0,0,...,360,163,369,165,NaN,,2.0,,NaN,
3,Aubameyang,Pierre-Emerick,1,NaN,NaN,54694,0,0,0,0,...,5,3,4,4,NaN,,4.0,,1.0,
4,Soares,Cédric,1,NaN,NaN,58822,0,0,0,0,...,259,123,276,126,NaN,,NaN,,NaN,

['assists',
 'bonus',
 'bps',
 'chance_of_playing_next_round',
 'chance_of_playing_this_round',
 'clean_sheets',
 'code',
 'corners_and_indirect_freekicks_order',
 'corners_and_indirect_freekicks_text',
 'cost_change_event',
 'cost_change_event_fall',
 'cost_change_start',
 'cost_change_start_fall',
 'creativity',
 'creativity_rank',
 'creativity_rank_type',
 'direct_freekicks_order',
 'direct_freekicks_text',
 'dreamteam_count',
 'element_type',
 'ep_next',
 'ep_this',
 'event_points',
 'first_name',
 'form',
 'goals_conceded',
 'goals_scored',
 'ict_index',
 'ict_index_rank',
 'ict_index_rank_type',
 'id',
 'in_dreamteam',
 'influence',
 'influence_rank',
 'influence_rank_type',
 'minutes',
 'news',
 'news_added',
 'now_cost',
 'own_goals',
 'penalties_missed',
 'penalties_order',
 'penalties_saved',
 'penalties_text',
 'photo',
 'points_per_game',
 'red_cards',
 'saves',
 'second_name',
 'selected_by_percent',
 'special',
 'squad_number',
 'status',
 'team',
 'team_code',
 'threat',
 'threat_rank',
 'threat_rank_type',
 'total_points',
 'transfers_in',
 'transfers_in_event',
 'transfers_out',
 'transfers_out_event',
 'value_form',
 'value_season',
 'web_name',
 'yellow_cards']

In [28]:
# Noe hacking av rekkefølge av index for å få ønskede verdier først
_elements_columns = elements_df_14.columns.tolist()
_elements_columns.insert(0, _elements_columns.pop(_elements_columns.index("team")))
_elements_columns.insert(0, _elements_columns.pop(_elements_columns.index("first_name")))
_elements_columns.insert(0, _elements_columns.pop(_elements_columns.index("second_name")))
elements_df_14 = elements_df_14[_elements_columns]
# Vis 5 første linjer
display(elements_df_14.head(5))

# Vis tilgjengelige kolonner
display(sorted(_elements_columns))

,second_name,first_name,team,chance_of_playing_next_round,chance_of_playing_this_round,code,cost_change_event,cost_change_event_fall,cost_change_start,cost_change_start_fall,...,threat_rank,threat_rank_type,ict_index_rank,ict_index_rank_type,corners_and_indirect_freekicks_order,corners_and_indirect_freekicks_text,direct_freekicks_order,direct_freekicks_text,penalties_order,penalties_text
0,Özil,Mesut,1,NaN,NaN,37605,0,0,0,0,...,501,198,504,200,3.0,,NaN,,NaN,
1,Papastathopoulos,Sokratis,1,0.0,0.0,39476,0,0,0,0,...,271,124,309,132,NaN,,NaN,,NaN,
2,Luiz Moreira Marinho,David,1,0.0,0.0,41270,0,0,0,0,...,385,168,402,171,NaN,,2.0,,NaN,
3,Aubameyang,Pierre-Emerick,1,NaN,NaN,54694,0,0,0,0,...,7,4,6,4,NaN,,4.0,,1.0,
4,Soares,Cédric,1,NaN,NaN,58822,0,0,0,0,...,287,130,321,137,NaN,,NaN,,NaN,

['assists',
 'bonus',
 'bps',
 'chance_of_playing_next_round',
 'chance_of_playing_this_round',
 'clean_sheets',
 'code',
 'corners_and_indirect_freekicks_order',
 'corners_and_indirect_freekicks_text',
 'cost_change_event',
 'cost_change_event_fall',
 'cost_change_start',
 'cost_change_start_fall',
 'creativity',
 'creativity_rank',
 'creativity_rank_type',
 'direct_freekicks_order',
 'direct_freekicks_text',
 'dreamteam_count',
 'element_type',
 'ep_next',
 'ep_this',
 'event_points',
 'first_name',
 'form',
 'goals_conceded',
 'goals_scored',
 'ict_index',
 'ict_index_rank',
 'ict_index_rank_type',
 'id',
 'in_dreamteam',
 'influence',
 'influence_rank',
 'influence_rank_type',
 'minutes',
 'news',
 'news_added',
 'now_cost',
 'own_goals',
 'penalties_missed',
 'penalties_order',
 'penalties_saved',
 'penalties_text',
 'photo',
 'points_per_game',
 'red_cards',
 'saves',
 'second_name',
 'selected_by_percent',
 'special',
 'squad_number',
 'status',
 'team',
 'team_code',
 'threat',
 'threat_rank',
 'threat_rank_type',
 'total_points',
 'transfers_in',
 'transfers_in_event',
 'transfers_out',
 'transfers_out_event',
 'value_form',
 'value_season',
 'web_name',
 'yellow_cards']

In [29]:
elements_df_13[['second_name','transfers_in',
 'transfers_in_event',
 'transfers_out',
 'transfers_out_event',]]

,second_name,transfers_in,transfers_in_event,transfers_out,transfers_out_event
0,Özil,250,250,2678,2678
1,Papastathopoulos,11,11,849,849
2,Luiz Moreira Marinho,88,88,5644,5644
3,Aubameyang,10390,10390,27121,27121
4,Soares,147,147,2198,2198
...,...,...,...,...,...
522,Cavaco Jordao,649,649,562,562
523,Campana,503,503,365,365
524,Silva,1927,1927,1043,1043
525,Marçal,144,144,169,169
526,Ferreira,39,39,45,45

In [30]:
elements_df_14[['second_name','transfers_in',
 'transfers_in_event',
 'transfers_out',
 'transfers_out_event',]]

,second_name,transfers_in,transfers_in_event,transfers_out,transfers_out_event
0,Özil,418,418,5175,5175
1,Papastathopoulos,16,16,1548,1548
2,Luiz Moreira Marinho,171,171,10117,10117
3,Aubameyang,24017,24017,57478,57478
4,Soares,256,256,3975,3975
...,...,...,...,...,...
522,Cavaco Jordao,1573,1573,1412,1412
523,Campana,1057,1057,902,902
524,Silva,3924,3924,2666,2666
525,Marçal,310,310,425,425
526,Ferreira,96,96,98,98

In [32]:
with open(Path(data_path, "2020-09-14T06-00-00Z_data.json")) as json_file:
        fpl_json_14_1 = json.load(json_file)
elements_df_14_1 = pd.DataFrame(fpl_json_14_1["elements"])

In [33]:
elements_df_14_1[['second_name','transfers_in',
 'transfers_in_event',
 'transfers_out',
 'transfers_out_event',]]

,second_name,transfers_in,transfers_in_event,transfers_out,transfers_out_event
0,Özil,443,443,5493,5493
1,Papastathopoulos,16,16,1627,1627
2,Luiz Moreira Marinho,178,178,10631,10631
3,Aubameyang,25277,25277,60830,60830
4,Soares,263,263,4208,4208
...,...,...,...,...,...
522,Cavaco Jordao,1644,1644,1503,1503
523,Campana,1110,1110,950,950
524,Silva,4143,4143,2841,2841
525,Marçal,335,335,466,466
526,Ferreira,105,105,112,112

In [35]:
_elements_columns

['second_name',
 'first_name',
 'team',
 'chance_of_playing_next_round',
 'chance_of_playing_this_round',
 'code',
 'cost_change_event',
 'cost_change_event_fall',
 'cost_change_start',
 'cost_change_start_fall',
 'dreamteam_count',
 'element_type',
 'ep_next',
 'ep_this',
 'event_points',
 'form',
 'id',
 'in_dreamteam',
 'news',
 'news_added',
 'now_cost',
 'photo',
 'points_per_game',
 'selected_by_percent',
 'special',
 'squad_number',
 'status',
 'team_code',
 'total_points',
 'transfers_in',
 'transfers_in_event',
 'transfers_out',
 'transfers_out_event',
 'value_form',
 'value_season',
 'web_name',
 'minutes',
 'goals_scored',
 'assists',
 'clean_sheets',
 'goals_conceded',
 'own_goals',
 'penalties_saved',
 'penalties_missed',
 'yellow_cards',
 'red_cards',
 'saves',
 'bonus',
 'bps',
 'influence',
 'creativity',
 'threat',
 'ict_index',
 'influence_rank',
 'influence_rank_type',
 'creativity_rank',
 'creativity_rank_type',
 'threat_rank',
 'threat_rank_type',
 'ict_index_rank',
 'ict_index_rank_type',
 'corners_and_indirect_freekicks_order',
 'corners_and_indirect_freekicks_text',
 'direct_freekicks_order',
 'direct_freekicks_text',
 'penalties_order',
 'penalties_text']

In [57]:
x = [{i:{"change":"None", "description":"None", "notes": "None"}} for i in sorted(_elements_columns)]

In [58]:
print(json.dumps(x, indent=4))

[
    {
        "assists": {
            "change": "None",
            "description": "None",
            "notes": "None"
        }
    },
    {
        "bonus": {
            "change": "None",
            "description": "None",
            "notes": "None"
        }
    },
    {
        "bps": {
            "change": "None",
            "description": "None",
            "notes": "None"
        }
    },
    {
        "chance_of_playing_next_round": {
            "change": "None",
            "description": "None",
            "notes": "None"
        }
    },
    {
        "chance_of_playing_this_round": {
            "change": "None",
            "description": "None",
            "notes": "None"
        }
    },
    {
        "clean_sheets": {
            "change": "None",
            "description": "None",
            "notes": "None"
        }
    },
    {
        "code": {
            "change": "None",
            "description": "None",
            "notes": "None"
        }
    },
    {
        "corners_and_indirect_freekicks_order": {
            "change": "None",
            "description": "None",
            "notes": "None"
        }
    },
    {
        "corners_and_indirect_freekicks_text": {
            "change": "None",
            "description": "None",
            "notes": "None"
        }
    },
    {
        "cost_change_event": {
            "change": "None",
            "description": "None",
            "notes": "None"
        }
    },
    {
        "cost_change_event_fall": {
            "change": "None",
            "description": "None",
            "notes": "None"
        }
    },
    {
        "cost_change_start": {
            "change": "None",
            "description": "None",
            "notes": "None"
        }
    },
    {
        "cost_change_start_fall": {
            "change": "None",
            "description": "None",
            "notes": "None"
        }
    },
    {
        "creativity": {
            "change": "None",
            "description": "None",
            "notes": "None"
        }
    },
    {
        "creativity_rank": {
            "change": "None",
            "description": "None",
            "notes": "None"
        }
    },
    {
        "creativity_rank_type": {
            "change": "None",
            "description": "None",
            "notes": "None"
        }
    },
    {
        "direct_freekicks_order": {
            "change": "None",
            "description": "None",
            "notes": "None"
        }
    },
    {
        "direct_freekicks_text": {
            "change": "None",
            "description": "None",
            "notes": "None"
        }
    },
    {
        "dreamteam_count": {
            "change": "None",
            "description": "None",
            "notes": "None"
        }
    },
    {
        "element_type": {
            "change": "None",
            "description": "None",
            "notes": "None"
        }
    },
    {
        "ep_next": {
            "change": "None",
            "description": "None",
            "notes": "None"
        }
    },
    {
        "ep_this": {
            "change": "None",
            "description": "None",
            "notes": "None"
        }
    },
    {
        "event_points": {
            "change": "None",
            "description": "None",
            "notes": "None"
        }
    },
    {
        "first_name": {
            "change": "None",
            "description": "None",
            "notes": "None"
        }
    },
    {
        "form": {
            "change": "None",
            "description": "None",
            "notes": "None"
        }
    },
    {
        "goals_conceded": {
            "change": "None",
            "description": "None",
            "notes": "None"
        }
    },
    {
        "goals_scored": {
            "change": "None",
            "description": "None",
            "notes": "None"
        }
    },
    {
        "ict_index": {
            "change": "None",
            "description": "None",
            "notes": "None"
        }
    },
    {
        "ict_index_rank": {
            "change": "None",
            "description": "None",
            "notes": "None"
        }
    },
    {
        "ict_index_rank_type": {
            "change": "None",
            "description": "None",
            "notes": "None"
        }
    },
    {
        "id": {
            "change": "None",
            "description": "None",
            "notes": "None"
        }
    },
    {
        "in_dreamteam": {
            "change": "None",
            "description": "None",
            "notes": "None"
        }
    },
    {
        "influence": {
            "change": "None",
            "description": "None",
            "notes": "None"
        }
    },
    {
        "influence_rank": {
            "change": "None",
            "description": "None",
            "notes": "None"
        }
    },
    {
        "influence_rank_type": {
            "change": "None",
            "description": "None",
            "notes": "None"
        }
    },
    {
        "minutes": {
            "change": "None",
            "description": "None",
            "notes": "None"
        }
    },
    {
        "news": {
            "change": "None",
            "description": "None",
            "notes": "None"
        }
    },
    {
        "news_added": {
            "change": "None",
            "description": "None",
            "notes": "None"
        }
    },
    {
        "now_cost": {
            "change": "None",
            "description": "None",
            "notes": "None"
        }
    },
    {
        "own_goals": {
            "change": "None",
            "description": "None",
            "notes": "None"
        }
    },
    {
        "penalties_missed": {
            "change": "None",
            "description": "None",
            "notes": "None"
        }
    },
    {
        "penalties_order": {
            "change": "None",
            "description": "None",
            "notes": "None"
        }
    },
    {
        "penalties_saved": {
            "change": "None",
            "description": "None",
            "notes": "None"
        }
    },
    {
        "penalties_text": {
            "change": "None",
            "description": "None",
            "notes": "None"
        }
    },
    {
        "photo": {
            "change": "None",
            "description": "None",
            "notes": "None"
        }
    },
    {
        "points_per_game": {
            "change": "None",
            "description": "None",
            "notes": "None"
        }
    },
    {
        "red_cards": {
            "change": "None",
            "description": "None",
            "notes": "None"
        }
    },
    {
        "saves": {
            "change": "None",
            "description": "None",
            "notes": "None"
        }
    },
    {
        "second_name": {
            "change": "None",
            "description": "None",
            "notes": "None"
        }
    },
    {
        "selected_by_percent": {
            "change": "None",
            "description": "None",
            "notes": "None"
        }
    },
    {
        "special": {
            "change": "None",
            "description": "None",
            "notes": "None"
        }
    },
    {
        "squad_number": {
            "change": "None",
            "description": "None",
            "notes": "None"
        }
    },
    {
        "status": {
            "change": "None",
            "description": "None",
            "notes": "None"
        }
    },
    {
        "team": {
            "change": "None",
            "description": "None",
            "notes": "None"
        }
    },
    {
        "team_code": {
            "change": "None",
            "description": "None",
            "notes": "None"
        }
    },
    {
        "threat": {
            "change": "None",
            "description": "None",
            "notes": "None"
        }
    },
    {
        "threat_rank": {
            "change": "None",
            "description": "None",
            "notes": "None"
        }
    },
    {
        "threat_rank_type": {
            "change": "None",
            "description": "None",
            "notes": "None"
        }
    },
    {
        "total_points": {
            "change": "None",
            "description": "None",
            "notes": "None"
        }
    },
    {
        "transfers_in": {
            "change": "None",
            "description": "None",
            "notes": "None"
        }
    },
    {
        "transfers_in_event": {
            "change": "None",
            "description": "None",
            "notes": "None"
        }
    },
    {
        "transfers_out": {
            "change": "None",
            "description": "None",
            "notes": "None"
        }
    },
    {
        "transfers_out_event": {
            "change": "None",
            "description": "None",
            "notes": "None"
        }
    },
    {
        "value_form": {
            "change": "None",
            "description": "None",
            "notes": "None"
        }
    },
    {
        "value_season": {
            "change": "None",
            "description": "None",
            "notes": "None"
        }
    },
    {
        "web_name": {
            "change": "None",
            "description": "None",
            "notes": "None"
        }
    },
    {
        "yellow_cards": {
            "change": "None",
            "description": "None",
            "notes": "None"
        }
    }
]